### ISSUE TITLE
Looks for log file without creating it

### ISSUE THREAD

**Issue by ltworf** [centaurialpha/pireal#10]
```
$ python pireal.py 
Traceback (most recent call last):
  File "pireal.py", line 36, in <module>
    logger = PirealLogger(__name__)
  File "/amem/pireal/src/core/logger.py", line 67, in __call__
    self._header)
  File "/amem/pireal/src/core/logger.py", line 88, in __init__
    backupCount, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 905, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 935, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/salvo/.pireal/pireal_log.log'
```

It crashes because there is no `.pireal` directory in my home.

**Comment by centaurialpha** [comment]
Fixed!
