### ISSUE TITLE
I pressed "delete column" and it all crashed

### ISSUE THREAD

**Issue by ltworf** [centaurialpha/pireal#13]
```
$ python3 pireal.py 
INFO:__main__:Executing Pireal from source
INFO:__main__:Python 3.4.4 - Qt 5.5.1 on Linux hal9000
INFO:__main__:Loading settings...
INFO:__main__:Loading GUI...
INFO:__main__:Pireal ready!
KSambaShare: Could not find smb.conf!
No node found for item that was just removed: QUrl("file:///amem/pireal/os")
Invalid URL: QUrl("untitled_1.pdb")
Invalid URL: QUrl("untitled_1.pdb")

Traceback (most recent call last):
  File "/amem/pireal/src/gui/dialogs/new_relation_dialog.py", line 144, in __remove_column
    self.__remove_from_layout(column_to_remove)
  File "/amem/pireal/src/gui/dialogs/new_relation_dialog.py", line 170, in __remove_from_layout
    widget = self._hbox.takeAt(index).widget()
AttributeError: 'NoneType' object has no attribute 'widget'
Annullato
```

I was editing a relation and I pressed "delete column".

**Comment by centaurialpha** [comment]
Fixed!
