### ISSUE TITLE
Another crash trying to run a query

### ISSUE THREAD

**Issue by ltworf** [centaurialpha/pireal#15]
```
$ python3 pireal.py 
INFO:__main__:Executing Pireal from source
INFO:__main__:Python 3.4.4 - Qt 5.5.1 on Linux hal9000
INFO:__main__:Loading settings...
INFO:__main__:Loading GUI...
INFO:__main__:Pireal ready!
KSambaShare: Could not find smb.conf!
DEBUG:src.gui.central_widget:Intentando abrir la base de datos '/amem/untitled_1.pdb'
DEBUG:src.gui.main_container:Base de datos importada con éxito
No node found for item that was just removed: QUrl("file:///amem/untitled_1.pdb")
org.kde.kurifilter-shorturi: "~salvo/dev/relational/samples/"
org.kde.kurifilter-shorturi: path = "/home/salvo/dev/relational/samples/"  isLocalFullPath= true  exists= true  url= QUrl("~salvo/dev/relational/samples/")
org.kde.kurifilter-ikws: "~salvo/dev/relational/samples/" : QUrl("file:///home/salvo/dev/relational/samples/") , type = 2
DEBUG:src.gui.query_container.query_container:Parseando la línea: people njoin  skills
DEBUG:src.gui.query_container.query_container:Ejecutando la expresión: people.njoin(skills)
DEBUG:src.gui.query_container.query_container:Parseando la línea: select  skill=='Python'( people njoin  skills)
ERROR:src.gui.query_container.query_container:Error al evaluar o ejecutar la expresión: 'Node' object has no attribute '_name'
Traceback (most recent call last):
  File "/amem/pireal/src/gui/central_widget.py", line 161, in execute_queries
    main_container.execute_queries()
  File "/amem/pireal/src/gui/main_container.py", line 238, in execute_queries
    self.query_container.execute_queries()
  File "/amem/pireal/src/gui/query_container/query_container.py", line 182, in execute_queries
    if table_widget.add_relation(relation_name, relation):
UnboundLocalError: local variable 'relation' referenced before assignment
Annullato
```

I have imported the relations from "relational" and I tried to run a query.

**Comment by centaurialpha** [comment]
Fixed!
